import React from "react";

// ─── Date helpers (same as existing system) ──────────────────────────────────
function formatDate(dateStr) {
  if (!dateStr) return "—";
  const d = new Date(dateStr);
  if (isNaN(d)) return "—";
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${String(d.getDate()).padStart(2,"0")}-${months[d.getMonth()]}-${String(d.getFullYear()).slice(-2)}`;
}
function formatDateISO(dateStr) {
  if (!dateStr) return "—";
  const d = new Date(dateStr);
  if (isNaN(d)) return "—";
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
}

// ─── Build the flat row list for a single enquiry ────────────────────────────
// Each enquiry expands into N rows: one row for the parent part, plus one
// row PER child part. The parent's own part/BO-part text is never duplicated —
// it appears once, in its own row. Inquiry No / Customer Name / RFQ Date /
// Item Description are repeated on every row (including child rows), while
// Supplier / PO Number / Date of Issue / Generated By / Generated On / Actions
// stay common for the whole group (rowSpan), since those aren't per-part fields.
function buildRows(enq) {
  const rows = [];

  // Index enq.partSuppliers by Customer Part No so each part's row can
  // pull its own list of assigned suppliers (each with its own PO Number).
  // Handles legacy string[] suppliers too, normalizing them to { name, poNumber }.
  const partSuppliersMap = {};
  (Array.isArray(enq.partSuppliers) ? enq.partSuppliers : []).forEach((ps) => {
    const list = Array.isArray(ps.suppliers) ? ps.suppliers : [];
    partSuppliersMap[ps.customerPartNo] = list.map((s) =>
      typeof s === "string"
        ? { name: s, poNumber: "", dateOfIssue: "" }
        : { name: s.name || "", poNumber: s.poNumber || "", dateOfIssue: s.dateOfIssue || "" }
    );
  });
  const resolveSuppliers = (partNo) => partSuppliersMap[partNo] || [];

  // Resolve parts array — fall back to partMapping for legacy records
  let parts = Array.isArray(enq.parts) && enq.parts.length > 0
    ? enq.parts
    : enq.partMapping?.customerPartNo
      ? [{ customerPartNo: enq.partMapping.customerPartNo, customerPartName: enq.partMapping.customerPartName, modifiedBOPartNo: enq.partMapping.modifiedBOPartNo, boPartName: enq.partMapping.boPartName, children: [] }]
      : [{ customerPartNo: "—", customerPartName: "", modifiedBOPartNo: "", boPartName: "", children: [] }];

  parts.forEach((parent) => {
    // Parent's own row
    rows.push({
      isChild:    false,
      partNo:     parent.customerPartNo   || "—",
      boPartName: parent.boPartName       || "",
      boPartNo:   parent.modifiedBOPartNo || "",
      suppliers:  resolveSuppliers(parent.customerPartNo),
    });

    // Every child gets its own separate row — same enquiry info repeated
    const children = Array.isArray(parent.children) ? parent.children : [];
    children.forEach((child) => {
      rows.push({
        isChild:    true,
        partNo:     child.customerPartNo   || "—",
        boPartName: child.boPartName       || "",
        boPartNo:   child.modifiedBOPartNo || "",
        suppliers:  resolveSuppliers(child.customerPartNo),
      });
    });
  });

  return rows;
}

// ─── Single enquiry rendered as grouped rows ──────────────────────────────────
function EnquiryRowGroup({ enq, onView, onEdit, onDownload }) {
  const rows = buildRows(enq);
  const totalRows = rows.length;
  // If this enquiry has any per-part supplier assignments, show Supplier/PO
  // per row (per part) instead of one merged cell for the whole enquiry — a part
  // can now have multiple suppliers, so a single shared cell can't represent that.
  const hasPartSuppliers = rows.some((r) => (r.suppliers || []).length > 0);

  return rows.map((row, rIdx) => {
    const isFirst = rIdx === 0;

    return (
      <tr
        key={`${enq._id}-${rIdx}`}
        className={`enq-row${isFirst ? " enq-row-first" : " enq-row-cont"}`}
      >

        {/* ── BO / ENQUIRY DETAILS: repeated in full on every row, including child-part rows ── */}
        <td className="enq-td enq-td-main enq-td-enqno">
          <span className="cell-badge">{enq.enquiryNumber || "—"}</span>
        </td>
        <td className="enq-td enq-td-main">
          {enq.customerName || "—"}
        </td>
        <td className="enq-td enq-td-main">
          {formatDateISO(enq.customerRFQDate)}
        </td>
        <td className="enq-td enq-td-main enq-td-desc">
          {enq.itemDescription
            ? enq.itemDescription.length > 32
              ? enq.itemDescription.slice(0, 32) + "…"
              : enq.itemDescription
            : "—"}
        </td>

        {/* ── CUSTOMER PART NO ── */}
        <td className="enq-td enq-td-part">
          <div className="part-cell">
            {row.isChild && <span className="part-tag child-tag">C</span>}
            <span className={`part-no${row.isChild ? " child-no" : ""}`}>
              {row.partNo}
            </span>
          </div>
        </td>

        {/* ── BO PART NAME ── */}
        <td className="enq-td">
          {row.boPartName ? (
            <span className={`part-no${row.isChild ? " child-no" : ""}`}>{row.boPartName}</span>
          ) : (
            <span className="enq-empty">—</span>
          )}
        </td>

        {/* ── BO PART NO ── */}
        <td className="enq-td">
          {row.boPartNo ? (
            <span className={`cell-bo-part${row.isChild ? " child-bo" : ""}`}>{row.boPartNo}</span>
          ) : (
            <span className="enq-empty">—</span>
          )}
        </td>

        {/* ── SUPPLIER ──
            When this enquiry has per-part supplier assignments, each row shows
            ITS OWN part's suppliers (a part can have more than one). Legacy enquiries
            with no partSuppliers data keep the old single merged cell. */}
        {hasPartSuppliers ? (
          <td className="enq-td">
            {row.suppliers && row.suppliers.length > 0 ? (
              <div className="supplier-cell-list">
                {row.suppliers.map((s, i) => (
                  <span className="cell-supplier-link" key={i}>{s.name}</span>
                ))}
              </div>
            ) : (
              <span className="enq-empty">—</span>
            )}
          </td>
        ) : (
          isFirst && (
            <td rowSpan={totalRows} className="enq-td enq-td-main">
              <span className="cell-supplier-link">
                {enq.poDetails?.supplierName || "—"}
              </span>
            </td>
          )
        )}

        {/* ── PO NUMBER ── same per-row logic as Supplier, paired 1:1 with each supplier above ── */}
        {hasPartSuppliers ? (
          <td className="enq-td">
            {row.suppliers && row.suppliers.length > 0 ? (
              <div className="supplier-cell-list">
                {row.suppliers.map((s, i) => (
                  <span key={i}>{s.poNumber ? <span className="cell-po">{s.poNumber}</span> : <span className="enq-empty">—</span>}</span>
                ))}
              </div>
            ) : (
              <span className="enq-empty">—</span>
            )}
          </td>
        ) : (
          isFirst && (
            <td rowSpan={totalRows} className="enq-td enq-td-main">
              {enq.poDetails?.poNumber
                ? <span className="cell-po">{enq.poDetails.poNumber}</span>
                : "—"}
            </td>
          )
        )}

        {/* ── DATE OF ISSUE ──
            Same per-row logic as Supplier/PO Number — when this enquiry has
            per-part supplier assignments, each row shows ITS OWN suppliers' dates of
            issue (paired 1:1 with each supplier above). Legacy enquiries with no
            partSuppliers data keep the old single merged cell (poDetails.dateOfIssue). */}
        {hasPartSuppliers ? (
          <td className="enq-td">
            {row.suppliers && row.suppliers.length > 0 ? (
              <div className="supplier-cell-list">
                {row.suppliers.map((s, i) => (
                  <span key={i}>{s.dateOfIssue ? <span className="cell-po">{formatDate(s.dateOfIssue)}</span> : <span className="enq-empty">—</span>}</span>
                ))}
              </div>
            ) : (
              <span className="enq-empty">—</span>
            )}
          </td>
        ) : (
          isFirst && (
            <td rowSpan={totalRows} className="enq-td enq-td-main">
              {formatDate(enq.poDetails?.dateOfIssue)}
            </td>
          )
        )}

        {/* ── GENERATED BY / ON (common per enquiry — not repeated per part) ── */}
        {isFirst && (
          <>
            <td rowSpan={totalRows} className="enq-td enq-td-main">
              <strong>{enq.generatedBy || "—"}</strong>
            </td>
            <td rowSpan={totalRows} className="enq-td enq-td-main">
              {formatDate(enq.createdAt)}
            </td>
          </>
        )}

        {/* ── ACTIONS (once per enquiry — not repeated per part) ── */}
        {isFirst && (
          <td rowSpan={totalRows} className="enq-td enq-td-main enq-td-actions">
            <div className="actions-cell">
              <button className="action-btn view" title="View" onClick={() => onView(enq)}>
                <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>
                </svg>
              </button>
              <button className="action-btn edit" title="Edit" onClick={() => onEdit(enq)}>
                <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/>
                </svg>
              </button>
              <button className="action-btn download" title="Download" onClick={() => onDownload(enq)}>
                <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
                </svg>
              </button>
            </div>
          </td>
        )}
      </tr>
    );
  });
}

// ─── Main EnquiryTable export ─────────────────────────────────────────────────
export default function EnquiryTable({
  enquiries,
  total,
  page,
  totalPages,
  onPageChange,
  onSort,
  sortField,
  sortOrder,
  onView,
  onEdit,
  onDownload,
  limit,
}) {
  const startRecord = (page - 1) * limit + 1;
  const endRecord   = Math.min(page * limit, total);

  const renderSortIcon = (field) => {
    if (sortField !== field) return null;
    return sortOrder === "asc" ? " ▲" : " ▼";
  };

  return (
    <>
      {/* ── Scoped styles for the grouped multi-row table ── */}
      <style>{`
        /* ── Table wrapper ── */
        .enq-table-outer {
          width: 100%;
          overflow-x: auto;
          border-radius: 10px;
          border: 1px solid #E5E7EB;
          background: #fff;
        }

        /* ── Table base ── */
        .enq-table {
          width: 100%;
          border-collapse: collapse;
          font-size: 11px;
          color: #1E293B;
        }

        /* ── Section header row (coloured band above column headers) ── */
        .enq-table thead tr.section-header th {
          padding: 4px 8px;
          font-size: 9px;
          font-weight: 700;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          border-bottom: none;
          white-space: nowrap;
        }
        .section-bo   { background: #EFF6FF; color: #1D4ED8; border-bottom: 2px solid #BFDBFE !important; }
        .section-part { background: #F5F3FF; color: #6D28D9; border-bottom: 2px solid #DDD6FE !important; }
        .section-po   { background: #F0FDF4; color: #15803D; border-bottom: 2px solid #BBF7D0 !important; }
        .section-gen  { background: #FFF7ED; color: #C2410C; border-bottom: 2px solid #FED7AA !important; }
        .section-act  { background: #F8FAFC; color: #475569; border-bottom: 2px solid #E2E8F0 !important; }

        /* ── Column headers ── */
        .enq-table thead tr.col-header th {
          padding: 6px 8px;
          font-size: 10.5px;
          font-weight: 600;
          color: #374151;
          background: #F9FAFB;
          border-bottom: 1.5px solid #E5E7EB;
          white-space: nowrap;
          cursor: pointer;
          user-select: none;
        }
        .enq-table thead tr.col-header th:hover { background: #F1F5F9; }

        /* ── Data cells ── */
        .enq-td {
          padding: 3px 8px;
          border-bottom: 1px solid #F1F5F9;
          vertical-align: top;
        }

        /* ── First row of each enquiry — slightly heavier top border ── */
        .enq-row-first .enq-td {
          border-top: 1px solid #E2E8F0;
          background: #FAFBFF;
        }
        /* Very first enquiry row in the table — no extra top border */
        .enq-table tbody tr:first-child .enq-td {
          border-top: none;
        }

        /* Continuation rows within the same enquiry */
        .enq-row-cont .enq-td {
          border-top: 1px dashed #F1F5F9;
          background: #fff;
        }

        /* Hover: highlight the whole enquiry group by setting a CSS var */
        .enq-row-first:hover .enq-td,
        .enq-row-cont:hover .enq-td {
          background: #F5F3FF;
        }

        /* ── Common/shared cell (spans multiple rows) ── */
        .enq-td-main {
          vertical-align: middle;
        }
        .enq-td-enqno { min-width: 90px; }
        .enq-td-desc  { max-width: 140px; }
        .enq-td-actions { min-width: 80px; vertical-align: middle; }

        /* ── Part cells ── */
        .enq-td-part  { min-width: 150px; }

        .part-cell {
          display: flex;
          align-items: center;
          gap: 4px;
          white-space: nowrap;
        }
        .part-tag {
          flex-shrink: 0;
          width: 15px;
          height: 15px;
          border-radius: 4px;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 8.5px;
          font-weight: 800;
          letter-spacing: 0;
        }
        .child-tag        { background: #C4B5FD; color: #3B0764; }

        .part-no {
          font-size: 11px;
          font-weight: 400;
          color: #1E293B;
          line-height: 1.3;
        }
        .part-no.child-no { color: #6D28D9; }

        .enq-empty { color: #D1D5DB; font-size: 11px; }

        /* ── Badges / chips (reuse existing classes, define fallbacks) ── */
        .cell-badge {
          display: inline-block;
          background: #DBEAFE;
          color: #1D4ED8;
          font-size: 10px;
          font-weight: 700;
          padding: 2px 7px;
          border-radius: 16px;
          letter-spacing: 0.02em;
          white-space: nowrap;
        }
        .cell-bo-part {
          display: inline-block;
          background: #FCE7F3;
          color: #9D174D;
          font-size: 10px;
          font-weight: 700;
          padding: 2px 7px;
          border-radius: 16px;
          white-space: nowrap;
        }
        .cell-bo-part.child-bo {
          background: #EDE9FE;
          color: #5B21B6;
        }
        .cell-supplier-link {
          color: #2563EB;
          font-weight: 500;
        }
        /* Stacks multiple supplier names / PO numbers vertically within one cell,
           so each line lines up with its counterpart in the neighboring column */
        .supplier-cell-list {
          display: flex;
          flex-direction: column;
          gap: 3px;
        }
        .supplier-cell-list .cell-supplier-link,
        .supplier-cell-list .cell-po,
        .supplier-cell-list .enq-empty {
          white-space: nowrap;
        }
        .cell-po {
          display: inline-block;
          background: #D1FAE5;
          color: #065F46;
          font-size: 10px;
          font-weight: 700;
          padding: 2px 7px;
          border-radius: 16px;
          white-space: nowrap;
        }

        /* ── Actions ── */
        .actions-cell { display: flex; gap: 4px; align-items: center; flex-wrap: wrap; }
        .action-btn {
          width: 22px;
          height: 22px;
          border-radius: 6px;
          border: 1.5px solid transparent;
          display: flex;
          align-items: center;
          justify-content: center;
          cursor: pointer;
          transition: all 0.15s;
          background: #F1F5F9;
          color: #475569;
        }
        .action-btn.view:hover   { background: #EFF6FF; border-color: #BFDBFE; color: #2563EB; }
        .action-btn.edit:hover   { background: #FEF3C7; border-color: #FDE68A; color: #B45309; }
        .action-btn.delete:hover { background: #FEF2F2; border-color: #FECACA; color: #DC2626; }
        .action-btn.download:hover { background: #F0FDF4; border-color: #BBF7D0; color: #15803D; }

        /* ── Empty state ── */
        .enq-empty-row td {
          padding: 32px 20px;
          text-align: center;
          color: #9CA3AF;
          font-size: 12px;
        }

        /* ── Pagination (reuse existing structure) ── */
        .enquiry-pagination {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 8px 12px;
          border-top: 1px solid #E5E7EB;
          background: #F9FAFB;
          border-radius: 0 0 10px 10px;
        }
        .pagination-info { font-size: 11.5px; color: #64748B; }
        .pagination-buttons { display: flex; gap: 6px; }
        .pagination-btn {
          height: 26px;
          padding: 0 10px;
          border: 1.5px solid #E2E8F0;
          border-radius: 6px;
          background: #fff;
          color: #374151;
          font-size: 11.5px;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.15s;
        }
        .pagination-btn:hover:not(:disabled) { background: #F1F5F9; border-color: #CBD5E1; }
        .pagination-btn:disabled { opacity: 0.4; cursor: not-allowed; }
      `}</style>

      <div className="enquiry-table-wrapper">
        <div className="enq-table-outer">
          <table className="enq-table">
            <thead>
              {/* Section colour bands */}
              <tr className="section-header">
                <th colSpan={4} className="section-bo">BO / Enquiry Details</th>
                <th colSpan={3} className="section-part">Part Number Mapping</th>
                <th colSpan={3} className="section-po">PO / Supplier</th>
                <th colSpan={2} className="section-gen">Generated</th>
                <th colSpan={1} className="section-act">Actions</th>
              </tr>
              {/* Column headers */}
              <tr className="col-header">
                {/* BO */}
                <th onClick={() => onSort("enquiryNumber")}>Inquiry No{renderSortIcon("enquiryNumber")}</th>
                <th onClick={() => onSort("customerName")}>Customer Name{renderSortIcon("customerName")}</th>
                <th onClick={() => onSort("customerRFQDate")}>RFQ Date{renderSortIcon("customerRFQDate")}</th>
                <th>Item Description</th>
                {/* Parts */}
                <th>Customer Part No</th>
                <th>BO Part Name</th>
                <th>BO Part No</th>
                {/* PO */}
                <th onClick={() => onSort("poDetails.supplierName")}>Supplier{renderSortIcon("poDetails.supplierName")}</th>
                <th onClick={() => onSort("poDetails.poNumber")}>PO Number{renderSortIcon("poDetails.poNumber")}</th>
                <th>Date of Issue</th>
                {/* Generated */}
                <th onClick={() => onSort("generatedBy")}>Generated By{renderSortIcon("generatedBy")}</th>
                <th onClick={() => onSort("createdAt")}>Generated On{renderSortIcon("createdAt")}</th>
                {/* Actions */}
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {enquiries.length === 0 ? (
                <tr className="enq-empty-row">
                  <td colSpan={13}>No enquiries found</td>
                </tr>
              ) : (
                enquiries.map((enq) => (
                  <EnquiryRowGroup
                    key={enq._id}
                    enq={enq}
                    onView={onView}
                    onEdit={onEdit}
                    onDownload={onDownload}
                  />
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination — identical props to existing EnquiryTable */}
        <div className="enquiry-pagination">
          <div className="pagination-info">
            Showing <strong>{startRecord}–{endRecord}</strong> of <strong>{total}</strong> records
          </div>
          <div className="pagination-buttons">
            <button className="pagination-btn" disabled={page <= 1} onClick={() => onPageChange(page - 1)}>
              ← Previous
            </button>
            <button className="pagination-btn" disabled={page >= totalPages} onClick={() => onPageChange(page + 1)}>
              Next →
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
